# cargo-about config for THIRD-PARTY-NOTICES.txt (installer/make-notices.ps1).
# For "A OR B" crates the first accepted license in this list is used.
accepted = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Zlib",
    "0BSD",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "MPL-2.0",
    "Unlicense",
]
targets = ["x86_64-pc-windows-msvc"]
ignore-build-dependencies = true
ignore-dev-dependencies = true
