<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Redline.Annotations</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Redline.Core\Redline.Core.csproj" />
    <ProjectReference Include="..\Redline.Windows\Redline.Windows.csproj" />
  </ItemGroup>
</Project>
